export const LOAD_USER = "LOAD_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RESET_AUTH = "RESET_AUTH";

export const GET_ALERTS = "GET_ALERTS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";

export const ADD_GOAL = "ADD_GOAL";
export const ADD_TODO = "ADD_TODO";
export const UPDATE_GOAL = "UPDATE_GOAL";
export const SET_GOALS = "SET_GOALS";
export const REMOVE_GOAL = "REMOVE_GOAL";
export const REMOVE_TODO = "REMOVE_TODO";
export const SET_CATEGORIES_FOR_GOAL = "SET_CATEGORIES_FOR_GOAL";
export const UPDATE_CATEGORY_FOR_GOAL = "UPDATE_CATEGORY_FOR_GOAL";
export const REMOVE_CATEGORY_FROM_GOALS = "REMOVE_CATEGORY_FROM_GOALS";

export const SET_ACTIVITIES = "SET_ACTIVITIES";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const REMOVE_ACTIVITY = "REMOVE_ACTIVITY";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";

export const ADD_REWARD = "ADD_REWARD";
export const REMOVE_REWARD = "REMOVE_REWARD";
export const SET_REWARDS = "SET_REWARDS";
export const FLIP_REWARDS = "FLIP_REWARDS";
